### ISSUE TITLE
TypeError at /admin/request/request/overview/

### ISSUE THREAD

**Issue by douglaskastle** [kylef/django-request#61]
Hi There

I installed django-requests today and got it working fine, that was until I tried to add REQUEST_IGNORE_PATHS to my setting it would bomb out with the warning below.  I am using Django 1.6.10 and Python 2.7.8.

I traced this back to the file in question and the paths are now being past in a unicode, not str, so this was causing the problems.

If I place this in my settings.py file:
````
REQUEST_IGNORE_PATHS = (
    r'^admin/$',
    r'^admin/request/(\.*)+',
)
````
and then in my local router.py, just inside the for loop, line 20, I add a print line:

    print(pattern, pattern__class__)

I get this output to my screen:

    (u'^admin/$', <type 'unicode'>)
    (u'^admin/request/(\\.*)+', <type 'unicode'>)

So based on this I fixed my local copy by changing line 21 in router.py from:

    if pattern.__class__ == str:

to:

    if pattern.__class__ == str or pattern.__class__ == unicode:

I don't know if this is the correct fix, but it works and correctly ignores the right paths.

````
Traceback Switch to copy-and-paste view

    ../lib/python2.7/site-packages/django/core/handlers/base.py in get_response

                        response = middleware_method(request, response)

        ...
    ▶ Local vars
    ../lib/python2.7/site-packages/request/middleware.py in process_response

                ignore = patterns(False, *settings.REQUEST_IGNORE_PATHS)

        ...
    ▶ Local vars
    ../lib/python2.7/site-packages/request/router.py in __init__

                        self.patterns.append(RegexPattern(*pattern))

````

**Comment by b3b** [comment]
This could happen when unicode_literals feature is used for Python 2. In settings.py :

    from __future__ import unicode_literals
    REQUEST_IGNORE_PATHS = (r'^admin/$',)

**Comment by ZuluPro** [comment]
It is related to PR #75 and #90.
The last one is ready, you can test it if you want.

**Comment by b3b** [comment]
With my settings, PR #90 fix the issue.

**Comment by ZuluPro** [comment]
@kylef This issue can be closed.
