### ISSUE TITLE
Mixed content warning when overview page is served over HTTPS

### ISSUE THREAD

**Issue by dwdyer** [kylef/django-request#83]
django-request always uses an HTTP URL for Google Charts, which leads to the browser marking the page as insecure due to mixed content.

Fixing this ought to be a simple as changing 
`'http://chart.apis.google.com/chart?cht=p3&chd=t:%s&chs=%sx%s&chl=%s'`
to
`'//chart.apis.google.com/chart?cht=p3&chd=t:%s&chs=%sx%s&chl=%s'`
in `request_admin.py`.

However, the google.com certificate doesn't include that sub-domain. To get around that, you can use the following instead:

`'//chart.googleapis.com/chart?cht=p3&chd=t:%s&chs=%sx%s&chl=%s'`

**Comment by ZuluPro** [comment]
@dwdyer I fixed your issue with PR #98 .
Can you try ?
